### ISSUE TITLE
Add support for CMake

### ISSUE THREAD

**Issue by jbcoe** [mikebmcl/P0267_RefImpl#40]
Many projects build using CMake. Would adding a CMakeLists.txt file be welcome?

**Comment by mikebmcl** [comment]
It would most certainly be welcome. It's been on my todo list for a while now but I haven't been able to find the time to do it yet. If you can spare time to create it, even if it's just for a single platform/generator, that would be most welcome, especially given that I do not have access to a Mac and it seems that Mac OS X is the last major desktop platform that is missing a good build experience with this project.

**Comment by jbcoe** [comment]
I'll take a look this week if time permits.

**Comment by mikebmcl** [comment]
The build system is now cmake thanks to @mikekazakov .
