### ISSUE TITLE
Library rather than executable

### ISSUE THREAD

**Issue by hatcat** [mikebmcl/P0267_RefImpl#41]
I have locally converted the RefImpl to a static library and the Asteroids game to an executable. It's quite trivial, being only a setting in the vcxproj file; is that all we need? Or do we want to add dynamic linking with this change?

**Comment by mikebmcl** [comment]
I think we'll want DLLs eventually, but a static library for now is good. Once you push the commit I'll try to revise the GNU Autotools build system to mirror the changes on the Windows side.

**Comment by hatcat** [comment]
OK, pushed. I'll keep this issue open to remind me to do the DLL version. That will take a little more time since I'll need to decorate the symbols to be exported with something like IO2D_API

**Comment by mikebmcl** [comment]
Excellent.

For the DLL version, I'd suggest _IO2D_API; since this is an implementation of a proposed, experimental standard library feature, we get to use reserved names here and it makes sense to use them where possible to minimize name collisions.

**Comment by hatcat** [comment]
Functions tagged. Additional VS solution configurations to follow.

**Comment by hatcat** [comment]
Added ONE dll configuration (dll_Debug). Failed curiously. Additionally, cairo failing to link. Spruced up the other configurations, so the only fails now are the dll configurations and the RocksInSpace clang configurations. Will attempt to solve tomorrow.

**Comment by hatcat** [comment]
Found some errors: misnamed the preprocessor symbol to trigger declspec decoration.
Still doesn't build.
How are the other libraries importing cairo? I see no directives.
Interestingly, dll_Debug|Win32 is looking for __imp_cairo* while dll_Debug|x64 is looking for __imp__cairo* which is unexpected: why the extra underscore?
Will try explicit import next.

**Comment by mikebmcl** [comment]
As best I can tell, vcpkg works on a basis where it is included in an
executable. I've created a separate branch to have the build system be
cmake which may solve the problem. For now, do a 'git stash push' then
create a branch for your DLL work that you pass the argument that does a
checkout for the new branch, then do a 'git stash pop' to restore your
changes, and commit it to that new  branch.

Or just copy it to a new directory on your machine and then carry on from
the latest commit. The only way to make that DLL work is to static link its
dependent libraries to it (which would bring along the LGPL if not the GPL,
or to copy the DLLs to the executable's directory.

-Mike

**Comment by mikebmcl** [comment]
Resolved by @hatcat .
