### ISSUE TITLE
Message queue callbacks

### ISSUE THREAD

**Issue by hatcat** [mikebmcl/P0267_RefImpl#43]
Taking charge of the message queue isn't going to fly: display_surface::begin_show and display_surface::end_show need to be joined by e.g. display_surface::update(time). The time parameter should be the time to advance by, defaulting to zero to allow the library to infer the elapsed time.

Ultimately, display_surface needs an additional constructor to pass a client window class. Perhaps the thing to do is to define an ABC for client windows and provide a default, although I am queasy about the idea of using such a technique for something known at compile time. Nonetheless, it's a starting point.

**Comment by mikebmcl** [comment]
I'm glad to say that we solved this. As I've said at various times, I'm very glad you agreed to jump aboard as a co-author. There are still outstanding issues, but I have little doubt that we will solve them in good order.
