### ISSUE TITLE
RAII instead of *close in APIs.

### ISSUE THREAD

**Issue by Xazax-hun** [mikebmcl/P0267_RefImpl#68]
Maybe it would be better to have RAII objects for figure rather than having the user explicitly close them.

**Comment by mikebmcl** [comment]
Doing so would eliminate the ability to access the individual path items contiguously using iterators, which in turn would heavily complicate the use of, e.g., the STL algorithms on sequences of multiple figures. The change could be made, but I'm satisfied with the current design for figures. That doesn't close the door to such a change. It just means that someone besides me would need to do the work to create an RAII-based figure API and then write up a proposal to replace the existing API with that new API.
