### ISSUE TITLE
Unimplemented arc_center, arc_start, and arc_end

### ISSUE THREAD

**Issue by AaronBallman** [mikebmcl/P0267_RefImpl#74]
xgraphicsmath.h has declarations for arc_start(), arc_end(), and arc_center() that accept a point, an angle, and another point, but these declarations do not have definitions. Only the functions accepting a fourth argument of a matrix are implemented.

**Comment by hatcat** [comment]
Thanks Aaron

Be advised that this repository has been forked to https://github.com/ISOCPP-2D/P0267_RefImpl; we are unaware of the status of this repository's owner at the moment. Should he reappear I will likely transfer ownership of this new repository to him.

I would be grateful if you would raise these issues in that repository.

Cheers,
G

**Comment by AaronBallman** [comment]
Happy to do so! It's filed under https://github.com/ISOCPP-2D/P0267_RefImpl/issues/3

**Comment by mikebmcl** [comment]
Closed as per ISOCPP-2D/P0267_RefImpl#3.
